honestHusband/crowdTell/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^photo/(?P<pk>\d+)/', PictureQuestionDetailView.as_view(), name="picture_detail"),
    url(r'^upload_picture/', PictureQuestionCreateView.as_view(), name="upload_picture"),
    url(r'^answer_question/(?P<question_id>\d+)/', AnswerCreateView.as_view(), name='answer_question'),
    url(r'^answer_random_question/', answer_random_question, name='answer_random_question'),
    url(r'^vote_result/(?P<question_id>\d+)/', submit_vote_result, name='submit_vote_result'),
    url(r'^person/(?P<pk>\d+)/', PersonDetailView.as_view(), name="person_detail"),
    url(r'person_bootstrapped/', bootstrapped_person_view, name="bootstrapped_person"),
    url(r'^create_person/', PersonCreateView.as_view(), name='create_person'),
    url(r'^search/', search, name='search'),
    url(r'^search_results/', search_results, name='search_results'),
    url(r'^add_friend', add_friend, name='add_friend'),
    url(r'^$', landing, name='landing'),
]

honestHusband/honestHusband/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from crowdTell import views
from crowdTell.views import MyRegistrationView
from honestHusband import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('crowdTell.urls', namespace='crowdTell'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

honestHusband/crowdTell/models.py
from __future__ import division
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Person(models.Model):
    user = models.ForeignKey(User)
    friends = models.ManyToManyField('self', symmetrical=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    @property
    def picture_questions(self):
        return PictureQuestion.objects.filter(person__id=self.id)

    def get_absolute_url(self):
        return reverse('crowdTell:person_detail', args=(self.id,))

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)


class PictureQuestion(models.Model):
    person = models.ForeignKey(Person)
    title = models.CharField(max_length=100, verbose_name='Question')
    text = models.TextField(verbose_name='Supplementary Details')
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/')
    upload_time = models.DateTimeField(auto_now_add=True)

    @property
    def get_total_votes(self):
        return Answer.objects.filter(picture_question__id=self.id).count()

    @property
    def get_yes_pct(self):
        yes_answers = Answer.objects.filter(picture_question__id=self.id, vote=True).count()
        total_answers = self.get_total_votes

        if total_answers >= 1:
            return round(yes_answers / total_answers * 100, 2)
        else:
            return 0

    def get_absolute_url(self):
        return reverse('crowdTell:submit_vote_result', args=(self.id,))

    def __unicode__(self):
        return u'picture by %s' % self.person


class Answer(models.Model):
    person = models.ForeignKey(Person)
    picture_question = models.ForeignKey('PictureQuestion')
    vote = models.BooleanField()
    comment = models.TextField()

    def get_absolute_url(self):
        return reverse('crowdTell:submit_vote_result', args=(self.picture_question.id,))

    def __unicode__(self):
        return u'%s on %s with %s' % (self.person, self.picture_question, self.vote)

honestHusband/crowdTell/forms.py
from django import forms
from django.forms import ModelForm, Form, FileField, CharField, Textarea

from .models import *


class PictureQuestionForm(ModelForm):
    class Meta:
        model = PictureQuestion
        fields = ['title', 'text', 'image']

    def __init__(self, *args, **kwargs):
        super(PictureQuestionForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'accept': 'image/*', 'capture': 'camera'})


class AnswerForm(ModelForm):
    vote = forms.BooleanField(required=False, initial=False)
    comment = forms.CharField(widget=forms.Textarea, label='')
    class Meta:
        model = Answer
        fields = ['vote', 'comment']

honestHusband/crowdTell/views.py
from random import randrange

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404


# Create your views here.
from django.views.generic import CreateView, DetailView
from registration.backends.simple.views import RegistrationView
from .forms import *
from .models import *
from django.db.models import Q


class PictureQuestionDetailView(DetailView):
    model = PictureQuestion
    context_object_name = 'picture'
    template_name = 'crowdTell/picture_detail_view.html'


class PictureQuestionCreateView(CreateView):
    form_class = PictureQuestionForm
    template_name = 'crowdTell/picture_create_view.html'

    def get_form(self, form_class=form_class):
        form = super(PictureQuestionCreateView, self).get_form(form_class)
        form.instance.person = get_object_or_404(Person, user__id=self.request.user.id)
        return form


class PersonDetailView(DetailView):
    model = Person
    context_object_name = 'person'
    template_name = 'crowdTell/person_detail_view.html'

    def get_context_data(self, **kwargs):
        context = super(PersonDetailView, self).get_context_data(**kwargs)
        user_person = get_object_or_404(Person, user__id=self.request.user.id)
        context['is_friend'] = (self.get_object() in user_person.friends.all()) or (user_person.id == self.get_object().id)
        return context


def bootstrapped_person_view(request):
    person = get_object_or_404(Person, user__id=request.user.id)
    return HttpResponseRedirect(reverse('crowdTell:person_detail', args=(person.id,)))

class PersonCreateView(CreateView):
    model = Person
    fields = ['first_name', 'last_name']
    template_name = 'crowdTell/generic_form.html'

    def get_form(self, form_class=None):
        form = super(PersonCreateView, self).get_form()
        form.instance.user = self.request.user
        return form

    def get_success_url(self):
        return reverse('crowdTell:upload_picture')


class AnswerCreateView(CreateView):
    form_class = AnswerForm
    template_name = 'crowdTell/answer_create_view.html'

    def dispatch(self, request, *args, **kwargs):
        self.picture_question = get_object_or_404(PictureQuestion, pk=kwargs['question_id'])
        if request.user.id == self.picture_question.person.user.id:
            return HttpResponseRedirect(reverse("crowdTell:submit_vote_result", args=(self.picture_question.id,)))

        return super(AnswerCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super(AnswerCreateView, self).get_context_data(**kwargs)
        context_data['picture_question'] = self.picture_question
        return context_data

    def get_form(self, form_class=None):
        form = super(AnswerCreateView, self).get_form()
        form.instance.person = get_object_or_404(Person, user__id=self.request.user.id)
        form.instance.picture_question = self.picture_question
        return form


def search(request):
    return render(request, 'crowdTell/search_view.html')


def search_results(request):
    print 'i am fucking here'
    search_criteria = request.POST['name_search']
    results = Person.objects.filter(Q(first_name__icontains=search_criteria) | Q(last_name__icontains=search_criteria))
    print results
    return render(request, 'crowdTell/search_results_view.html', {'results': results})


def landing(request):
    return render(request, 'crowdTell/landing.html', {})


def submit_vote_result(request, *args, **kwargs):
    picture_question = get_object_or_404(PictureQuestion, pk=kwargs['question_id'])
    return render(request, 'crowdTell/submit_vote_view.html', {'picture_question': picture_question})


class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return reverse('crowdTell:create_person',)


def answer_random_question(request):
    number_of_questions = PictureQuestion.objects.all().count()
    question_id = randrange(1, number_of_questions + 1)
    return HttpResponseRedirect(reverse('crowdTell:answer_question', args=(question_id,)))


def add_friend(request):
    friend_id = request.GET['friend_id']
    person = get_object_or_404(Person, user__id=request.user.id)
    potential_friend = get_object_or_404(Person, id=friend_id)
    person.friends.add(potential_friend)
    person.save()

    return HttpResponseRedirect(reverse('crowdTell:person_detail', args=(friend_id,)))

honestHusband/crowdTell/templates/crowdTell/answer_create_view.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% block content %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#id_vote").hide();
            $("#id_vote").parent().hide();
        });

        function submit_form(vote) {
            document.getElementById("id_vote").checked = vote;
            document.forms["answer_form"].submit();
        }
    </script>
    <h1>{{ picture_question.title }}</h1>
        <img src="{{ picture_question.image.url }}" width="300" height="300">
    <form id="answer_form" action="." method="post">
        <p>
            <input type="hidden" id="vote_result" name="vote_result"/>
            {% csrf_token %}
            {{ form|crispy }}
        </p>
    </form>
    <span class="glyphicon glyphicon-thumbs-down vote" onclick="submit_form(false)" aria-hidden="true"></span>
    <span class="glyphicon glyphicon-thumbs-up vote" onclick="submit_form(true)" aria-hidden="true"></span>
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/find_friends_view.html
{% extends 'base.html' %}

{% block content %}
    <h1>Search for Friends</h1>
    <form action="{% url 'crowdTell:search_for_friends' %}" method="post">{% csrf_token %}
        <label for="username">Friend's Username</label>
        <input type="text" id="username" name="username">
        <input type="submit" value="Search"/>
    </form>
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/generic_form.html
{% extends 'base.html' %}

{% block content %}
<form action="." method="post" style="margin-top:40px; max-width:50px;">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/landing.html
{% extends 'base.html' %}

{% block extra_styles %}
{% endblock extra_styles %}

{% block content %}
<div class="jumbotron">
    <h1>Welcome to Honest Husband!</h1>

    <p class="lead responsive_headline">
        Get an honest answer to the age-old question, "Does this make my ass look fat?"
        Take a picture of a new pair of pants (or anything else) you're debating and let the mob decide, yes or no!
        Connect with facebook to get answers from your friends!
    </p>

    <p>
        <a class="btn btn-lg btn-success" href="/accounts/register/" role="button">Sign up today</a>
    </p>
</div>

<footer class="footer">
    <p>&copy; The Djuggernauts 2015</p>
</footer>
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/person_detail_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block extra_scripts %}
    <script>
    function addFriend() {
        location.replace("{% url 'crowdTell:add_friend' %}?friend_id={{person.id}}");
    };
    </script>
{% endblock extra_scripts %}

{% block content %}
    <h1>{{person.first_name}} {{person.last_name}}'s profile</h1>
        {% if not is_friend %}
            <button id="addFriend" onclick="addFriend();" class="btn btn-success">Add Friend</button>
        {% endif %}
    {% for picture_question in person.picture_questions %}
    <div class="well">
        <h2>{{picture_question.title}}</h2>
            <img src="{{ picture_question.image.url }}" width="300" height="300">
        <h4>{{picture_question.text}}</h4>
    </div>
    {% endfor %}

{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/picture_create_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="cover-heading">Choose an image to get information:</h1>

<div class="form-group">
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit" class="btn btn-primary btn-lg"/>
    </form>
</div>


{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/picture_detail_view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
        <img src="{{picture.image.url}}">
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/picture_vote_view.html
{% extends 'base.html' %}

{% block content %}
    <script type="text/javascript">
        function submitVote(e) {
            document.getElementById("vote_result").value = e.value;
            document.forms["vote_form"].submit();
        }
    </script>
    <form id="vote_form" action="{% url 'crowdTell:submit_vote_result' %}" method="post">{% csrf_token %}
        <h1>{{ question.title }}</h1>
        <input type="hidden" id="vote_result" name="vote_result"/>
        <img src="{{ question.picture.image.url }}"/>
    </form>
    <br/>
    <button onclick="submitVote(this)" value="false">No</button><button onclick="submitVote(this)" value="true">Yes</button>
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/search_for_friends_view.html
{% extends 'base.html' %}

{% block content %}
    {{ friend_username }}
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/search_results_view.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    <div style="margin-top:40px;"></div>
    {% if results|length > 0 %}
        {% for person in results %}
            <a href="{% url 'crowdTell:person_detail' person.id %}"><h3>{{ person.first_name }} {{ person.last_name }}</h3></a>
            <br />
        {% endfor %}
    {% else %}
        <h3>No Results</h3>
    {% endif %}
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/search_view.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    <h1>Search For Friends</h1>
    <form action="{% url 'crowdTell:search_results' %}" method="post">
        {% csrf_token %}
        <label for="name_search">Name</label>
        <input type="text" id="name_search" required="true" name="name_search"/>
        <input type="submit" value="Search"/>
    </form>
{% endblock content %}

honestHusband/crowdTell/templates/crowdTell/submit_vote_view.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>{{ picture_question.title }}</h1>
        <img src="{{ picture_question.image.url }}" width="300" height="300">
        <br />
        Rating: {{ picture_question.get_yes_pct }}%
        <br />
        {{ picture_question.get_total_votes }} Votes
    </div>
{% endblock content %}