honestHusband/crowdTell/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^photo/(?P<pk>\d+)/', PictureQuestionDetailView.as_view(), name="picture_detail"),
    url(r'^upload_picture/', PictureQuestionCreateView.as_view(), name="upload_picture"),
    url(r'^answer_question/(?P<question_id>\d+)/', AnswerCreateView.as_view(), name='answer_question'),
    url(r'^answer_random_question/', answer_random_question, name='answer_random_question'),
    url(r'^vote_result/(?P<question_id>\d+)/', submit_vote_result, name='submit_vote_result'),
    url(r'^person/(?P<pk>\d+)/', PersonDetailView.as_view(), name="person_detail"),
    url(r'person_bootstrapped/', bootstrapped_person_view, name="bootstrapped_person"),
    url(r'^create_person/', PersonCreateView.as_view(), name='create_person'),
    url(r'^search/', search, name='search'),
    url(r'^search_results/', search_results, name='search_results'),
    url(r'^add_friend', add_friend, name='add_friend'),
    url(r'^$', landing, name='landing'),
]

honestHusband/honestHusband/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from crowdTell import views
from crowdTell.views import MyRegistrationView
from honestHusband import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('crowdTell.urls', namespace='crowdTell'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

honestHusband/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>{% block title %}Honest Husband{% endblock title %}</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'black.css' %}" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

    {% block extra_scripts %}{% endblock extra_scripts %}
    {% block extra_styles %}{% endblock extra_styles %}
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Honest Husband</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'crowdTell:upload_picture' %}">Ask</a></li>
            <li><a href="{% url 'crowdTell:answer_random_question' %}">Answer</a></li>
            <li><a href="{% url 'crowdTell:search' %}">Add Friends</a></li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'crowdTell:bootstrapped_person' %}">Profile</a></li>
                <li><a href="{% url 'auth_logout' %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
            {% else %}
                <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Login</a></li>
                <li><a href="{% url 'registration_register' %}">Signup</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="content">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>